packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@clerk/shared': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true
